sudo: required

services:
  - docker

before_install:
  - docker -v

script:
  - docker login -u ${REGISTRY_USER} -p ${REGISTRY_PASSWORD}
  - docker ps
#  - docker pull k8s.gcr.io/etcd
#  - docker pull k8s.gcr.io/hyperkube
